version: '3.8'

services:
    webapp:
        build:
            context: .
            dockerfile: app.dockerfile
        restart: always
        ports:
            - "5789:4173"
        # volumes:
        #     - ${PWD}/prisma/dev.db:/app/prisma/prod.db
    fs:
        build:
            context: .
            dockerfile: fs.dockerfile
        restart: always
        ports:
            - "5790:5790"
        volumes:
            - ${PWD}/data/audios/:/app/static/audios/